apiVersion: v1
kind: Service
metadata:
  name: inventory-api
spec:
  selector:
    app: inventory-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: hopdinhp02/ticketsales-inventoryapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__Database
          value: "Host=postgres-shared;Port=5432;Database=inventory_db;Username=user;Password=password"
        - name: Authentication__Authority
          value: "http://identity-api:8080"
        - name: MessageBroker__Host
          value: "rabbitmq"