{
 "title": "Dotnet Runtime Metrics",
 "description": "Runtime metrics for .NET applications using either .NET 9+ built-in metrics or OpenTelemetry.Instrumentation.Runtime package (for .NET 6/7/8). CPU metrics require .NET 9+.",
 "tags": [ ".net" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({__name__=~\"dotnet_assembly_count|process_runtime_dotnet_assemblies_count\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"dotnet_assembly_count|process_runtime_dotnet_assemblies_count\",job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Exceptions and Assemblies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thrown Exceptions",
     "type": "table",
     "description": "These include both handled and unhandled exceptions!",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Exceptions" } },
     "targets": [
      {
       "expr": "  topk(10,\r\n  sum by (error_type, job) (\r\n    ceil(increase({__name__=~\"dotnet_exceptions_total|process_runtime_dotnet_exceptions_count_total\", job=~\"$job\", instance=~\"$instance\"}[$__range]))\r\n  ))",
       "legendFormat": "{{error_type}}"
      }
     ]
    },
    {
     "title": "Assemblies by Job",
     "type": "table",
     "description": "The total number of .NET assemblies loaded into the process.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Assemblies" } },
     "targets": [
      {
       "expr": "avg by (job) ({__name__=~\"dotnet_assembly_count|process_runtime_dotnet_assemblies_count\", job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": ".NET GC and Memory [$job]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "job" },
  {
   "title": ".NET GC Pause Time",
   "type": "timeseries",
   "description": "Total amount of seconds the GC was paused in each process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(dotnet_gc_pause_time_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range])) or sum by (job) (irate(process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range]) / 1e9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".NET GC Collection Attempts",
   "type": "timeseries",
   "description": "Number of GC collection attempts per generation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "collections" } },
   "targets": [
    {
     "expr": "sum by (job, gc_heap_generation) (ceil(irate({__name__=~\"dotnet_gc_collections_total|process_runtime_dotnet_gc_collections_count_total\", job=~\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{job}} - {{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": ".NET GC Memory Committed",
   "type": "timeseries",
   "description": "The amount of physical memory in-use inside each .NET process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ({__name__=~\"dotnet_gc_last_collection_memory_committed_size_bytes|process_runtime_dotnet_gc_committed_memory_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": ".NET GC Heap Fragmentation",
   "type": "timeseries",
   "description": "Memory fragmentation in the managed heap, per-GC generation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, gc_heap_generation) ({__name__=~\"dotnet_gc_last_collection_heap_fragmentation_size_bytes|process_runtime_dotnet_gc_heap_fragmentation_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": ".NET GC Last Collection Heap Size",
   "type": "timeseries",
   "description": "The size of each of the managed heaps, following their last GC collection attempt.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, gc_heap_generation) ({__name__=~\"dotnet_gc_last_collection_heap_size_bytes|process_runtime_dotnet_gc_heap_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{gc_heap_generation}}"
    }
   ]
  },
  { "title": "CPU and ThreadPool [$job]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "job" },
  {
   "title": ".NET ThreadPool Workload",
   "type": "timeseries",
   "description": "Number of work items completed by the .NET managed ThreadPool on this [$job]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "items" } },
   "targets": [
    {
     "expr": "sum by (job) (floor(irate({__name__=~\"dotnet_thread_pool_work_item_count_total|process_runtime_dotnet_thread_pool_completed_items_count_total\", job=~\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{job}} completed items"
    }
   ]
  },
  {
   "title": ".NET ThreadPool Threads and Timers",
   "type": "timeseries",
   "description": "Number of .NET ThreadPool threads and timers on [$job]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by(job) ({__name__=~\"dotnet_thread_pool_thread_count_total|process_runtime_dotnet_thread_pool_threads_count\", job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}} threads"
    },
    {
     "expr": "sum by(job) ({__name__=~\"dotnet_timer_count|process_runtime_dotnet_timer_count\", job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}} timers"
    }
   ]
  },
  {
   "title": "CPU Seconds by Job",
   "type": "timeseries",
   "description": "âš ï¸ Requires .NET 9+ built-in metrics (not available in OpenTelemetry.Instrumentation.Runtime package for .NET 6/7/8).\n\nThe amount of CPU time used by instances of [$job]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, cpu_mode) (irate(dotnet_process_cpu_time_seconds_total{job=~\"$job\"}[$__range]))",
     "legendFormat": "{{job}} [{{cpu_mode}}]"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "table",
   "description": "âš ï¸ Requires .NET 9+ built-in metrics (not available in OpenTelemetry.Instrumentation.Runtime package for .NET 6/7/8).\n\nAll logical CPUs available to this process - these are shared with other processes running on the same machine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Logical CPUs" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (dotnet_process_cpu_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}/{{job}} CPU"
    }
   ]
  },
  { "title": ".NET JIT [$job]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "job" },
  {
   "title": ".NET JIT Compilation Time",
   "type": "timeseries",
   "description": "Total amount of time spent by the .NET Just-in-Time (JIT) compiler.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job) (irate(dotnet_jit_compilation_time_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range])) or sum by(job) (irate(process_runtime_dotnet_jit_compilation_time_nanoseconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range]) / 1e9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".NET JIT Compilations",
   "type": "timeseries",
   "description": "Determined by the total number of methods compiled by the .NET Just-in-Time (JIT) compiler.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "compilations" } },
   "targets": [
    {
     "expr": "sum by (job) (ceil(irate({__name__=~\"dotnet_jit_compiled_methods_total|process_runtime_dotnet_jit_methods_compiled_count_total\", job=~\"$job\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".NET JIT Compiled IL Bytes",
   "type": "timeseries",
   "description": "Total amount of .NET IL bytes emitted by the JIT.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ({__name__=~\"dotnet_jit_compiled_il_size_bytes_total|process_runtime_dotnet_jit_il_compiled_size_bytes_total\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}