apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  selector:
    app: identity-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
spec:
  replicas: {{ .Values.identityApi.replicas }}
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: "{{ .Values.identityApi.image.repository }}:{{ .Values.identityApi.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: IdentityServer__IssuerUri
          value: "http://identity-api:8080"