apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  selector:
    app: notifications-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api-deployment
spec:
  replicas: {{ .Values.notificationsApi.replicas }}
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: "{{ .Values.notificationsApi.image.repository }}:{{ .Values.notificationsApi.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: MessageBroker__Host
          value: "rabbitmq"